global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'service-registry'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['service-registry:8761']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'student-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['student-service:8081']

  - job_name: 'teacher-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['teacher-service:8082']

  - job_name: 'grade-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['grade-service:8083']

  - job_name: 'enrollment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['enrollment-service:8084']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8085']

  - job_name: 'module-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['module-service:8086']

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8090']
